CREATE TABLE ToDoItem (
  Id INT IDENTITY(1,1),
  Name NVARCHAR(64) NOT NULL,
  Description NVARCHAR(256) NULL,
  Priority TINYINT NOT NULL,
  CreatedAt DATETIME2(7) NOT NULL,
  IsDone BIT NOT NULL DEFAULT 0,
  CONSTRAINT PK_ToDoItem_Id PRIMARY KEY (Id),
  CONSTRAINT CK_ToDoItem_Priority CHECK (priority BETWEEN 1 AND 3)
);